# Persistence volume for azure kubernetes service.
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-pv
  labels:
    app: postgres
provisioner: file.csi.azure.com # Recommended CSI provisioner
parameters:
  skuName: Standard_LRS # Options: Standard_LRS, Standard_GRS, Premium_LRS
reclaimPolicy: Retain # Options: Retain, Delete
volumeBindingMode: Immediate # Immediate binding of volumes