# Persistence volume for azure kubernetes service.
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: staticfiles-pv
  labels:
    app: django-staticfiles
provisioner: kubernetes.io/azure-file
parameters:
  skuName: Standard_LRS # Options: Standard_LRS, Standard_GRS, Premium_LRS
reclaimPolicy: Retain # Options: Retain, Delete
volumeBindingMode: Immediate